[package]
name = "video_thumb_native"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
v_frame = "0.3.8"
symphonia = "0.5.4"
image = "0.24.5"
